import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

const router = new Router({
  routes: [
    {
      path: '/',
      redirect:'/page'
    },
    {
      path:'/page',
      name:'Page',
      component:resolve=>require(['@/subpage/page'],resolve)
    },
    {
      path:'/release',//急速发票
      name:'Release',
      component:resolve=>require(['@/subpage/release'],resolve),
      children:[
        {
          path:'/release/data',//我的数据
          name:'Data',
          component:resolve=>require(['@/subpage/person_data'],resolve)
        },
        {
          path:'/release/trad',//平台担保交易
          name:'Trad',
          component:resolve=>require(['@/subpage/platform_trading'],resolve)
        },
        {
          path:'/release/sell',//用户出售的票据
          name:'Sell',
          component:resolve=>require(['@/subpage/person_sell'],resolve)
        },
        {
          path:'/release/buy',//用户买入的票据
          name:'Buy',
          component:resolve=>require(['@/subpage/person_buy'],resolve)
        },
        {
          path:'/release/audit',//用户审核中的票据
          name:'Audit',
          component:resolve=>require(['@/subpage/person_audit'],resolve)
        },
        {
          path:'/release/offer',//用户发布的报价
          name:'ReOffer',
          component:resolve=>require(['@/subpage/person_offer'],resolve)
        },
        {
          path:'/release/mes',//用户消息
          name:'Mes',
          component:resolve=>require(['@/subpage/person_mes'],resolve)
        },
        {
          path:'/release/pass',//用户修改密码
          name:'Pass',
          component:resolve=>require(['@/subpage/person_pass'],resolve)
        },
        {
          path:'/release/detailed',//买家购买票据详情
          name:'Detailed',
          component:resolve=>require(['@/subpage/person_detailed'],resolve)
        },
        {
          path:'/release/repid',//急速发票
          name:'Repid',
          component:resolve=>require(['@/subpage/release_paper_rapid'],resolve)
        },
        {
          path:'/release/prise',//用户个人企业资料
          name:'Prise',
          component:resolve=>require(['@/subpage/person_prise'],resolve)
        },
        {
          path:'/release/order',//买家资源池
          name:'Order',
          component:resolve=>require(['@/subpage/person_order'],resolve)
        },
        {
          path:'/release/template',//报价模板
          name:'Template',
          component:resolve=>require(['@/subpage/offer_template'],resolve)
        }
      ],
      redirect:'/release/data'
    },
    {
      path:'/signIn',//注册
      name:'SignIn',
      component:resolve=>require(['@/subpage/signIn'],resolve)
    },
    {
      path:'/signUp',//登录
      name:'SignUp',
      component:resolve=>require(['@/subpage/signUp'],resolve),
      children:[
        {
          path:'/signUp/password',//密码登录
          name:'Password',
          component:resolve=>require(['@/components/password_signup'],resolve)
        },
        {
          path:'/signUp/auth',//验证码登录
          name:'Auth',
          component:resolve=>require(['@/components/auth_signup'],resolve)
        }
      ],
      redirect:'/signUp/auth'
    },
    {
      path:'/releasepa',//发布票据
      name:'ReleasePa',
      component:resolve=>require(['@/subpage/release_paper'],resolve)
    },
    {
      path:'/marketpa',//票据市场
      name:'MarketPa',
      component:resolve=>require(['@/subpage/market_paper'],resolve)
    },
    {
      path:'/details',//票据详情
      name:'Details',
      component:resolve=>require(['@/subpage/paper_details'],resolve)
    },
    {
      path:'/offer',//通知买家已报价
      name:'Offer',
      component:resolve=>require(['@/subpage/already_offer'],resolve)
    },
    {
      path:'/nooffer',//通知买家未报价
      name:'NoOffer',
      component:resolve=>require(['@/subpage/no_offer'],resolve)
    },
    {
      path:'/resources',//资源市场
      name:'Resources',
      component:resolve=>require(['@/subpage/market_resources'],resolve)
    }
  ]
});
export default router;
